[package]
name = "aplite_storage"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aplite_types = { path = "../aplite_types" }
