[package]
name = "aplite_future"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# aplite_storage = { path = "../aplite_storage" }
